

const Types = {
  SET_SECTION_LIST: 'SET_SECTION_LIST',
  ADD_SECTION_ITEM: 'ADD_SECTION_ITEM',
  DELETE_SECTION_ITEM: 'DELETE_SECTION_ITEM',
  UPDATE_SECTION_ITEM: 'UPDATE_SECTION_ITEM'
}

export default Types